version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: candidate-management-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: candidate_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - candidate-management-dev-network

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: candidate-management-api-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: candidate_management
    depends_on:
      - postgres
    networks:
      - candidate-management-dev-network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_dev_data:

networks:
  candidate-management-dev-network:
    driver: bridge
